# Generated by Django 4.0.6 on 2022-08-13 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='challenge_list',
            new_name='challenge_list_Model',
        ),
    ]
